development:
  adapter: postgresql
  database: devfolio_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: devfolio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: devfolio_production
  pool: 5
  timeout: 5000
